### ISSUE TITLE
gechi-overlay alias

### ISSUE THREAD

**Issue by bpinto** [Dr-Terrible/ineluctable-overlay#25]
When upgrading gcc to 6.4, I have seen this warning:

```
* Switching native-compiler to x86_64-pc-linux-gnu-6.4.0 ...!!! Section 'gechi-overlay' in repos.conf has name different from repository name 'ineluctable-overlay' set inside repository
```

The only reference to this name on the code was on the [layout](https://github.com/Dr-Terrible/ineluctable-overlay/blob/f8c971124afc27cbaa3335444487a44c603ef6d0/metadata/layout.conf) file: `aliases = gechi-overlay`.

Do you know why I am receiving this warning if this is only an alias?

**Comment by Dr-Terrible** [comment]
I have no idea, but at the same time I'm not so surprised by the warning. Pretty much all the Portage's tools are a bundle of mysteries wrapped in thick layers of stupidity :D 

It could be a Portags's bug, or simply the "alias" is not an alias despite what the doc says, sgrunt.

On a side note, the alias is not required any more and could be safely removed. It was necessary years ago because the `gechi` overlay belonged to the `Gentoo CHannel Italia` organization, which closed around ~2010 and its overlay was conflated with mine to keep it working.
