### ISSUE TITLE
Polybar (Lemonbuddy)

### ISSUE THREAD

**Issue by bpinto** [Dr-Terrible/ineluctable-overlay#4]
Hey, thanks for the overlay!

Lemonbuddy has been renamed to polybar and the ebuild does not work anymore.

It also requires gcc newer than 5.1, how can I install it along with latest unmasked 4.x version?

**Comment by Dr-Terrible** [comment]
Thank you for the report, @bpinto.

> Lemonbuddy has been renamed to polybar and the ebuild does not work anymore.

Oh gosh, I didn't notice it. I'll fix the ebuild ASAP.
The fix is trivial and you should be able to see a new commit in the next couple of hours.

> It also requires gcc newer than 5.1, how can I install it along with latest unmasked 4.x version?

It's quite simple if you use the [autounmask](https://wiki.gentoo.org/wiki/Knowledge_Base:Unmasking_a_package#Using_--autounmask-write) option of `emerge`.
However, if you want to do it manually:

```shell
$ cat /etc/portage/package.keywords/gcc 
# GCC 5.4
sys-devel/gcc:5.4.0

$ emerge -av gcc:5.4.0
```

**Comment by Dr-Terrible** [comment]
@bpinto in case you already have the old `lemonbuddy` package installed, run an `emerge -puDNv @world @system` and you should see something like this at the beginning of the output:

```shell
Performing Global Updates
(Could take a couple of minutes if you have a lot of binary packages.)
  .='update pass'  *='binary update'  #='/var/db update'  @='/var/db move'
  s='/var/db SLOT move'  %='binary move'  S='binary SLOT move'
  p='update /etc/portage/package.*'
/path/to/your/overlays/ineluctable-overlay/profiles/updates/4Q-2016.
```
then run `dispatch-conf` an the tool will change all the references inside your `/etc/portage/*` files from `x11-misc/lemonbuddy` to `x11-misc/polybar`. At that point, you can safely upgrade the package without worrying about the old ebuilds; emerge will take care of everything.

Instead, if you haven't previously installed `x11-misc/lemonbuddy`, just execute the standard  `emerge -av x11-misc/polybar`.

Let me know if there are missing parts, or if the ebuild needs to be further tweaked for specific features ;)

**Comment by bpinto** [comment]
Won't that `gcc` unmask remove my old gcc (4.x)?

**Comment by Dr-Terrible** [comment]
> Won't that gcc unmask remove my old gcc (4.x)?
Update: gcc is one of those packages that will auto install in a new slot.

Yup, gcc is a slotted package, so the various versions will be installed all together without removing the previous one (you need to explicitly remove them with `emerge -C gcc:<slot>`). Then you use `gcc-config` to globally select the desired version.

Beware about [gcc 5.x globally enabling C++1x](https://wiki.gentoo.org/wiki/Upgrading_GCC#The_special_case_C.2B.2B11_.28and_C.2B.2B14.29), as some packages (especially the very old ones) are not guarantee to compile with the new API/ABI change;  that is why gcc:5 is not a stable package at the moment ;)

Be sure to follow the proper [guide](https://wiki.gentoo.org/wiki/Upgrading_from_gcc-4.x_to_gcc-5.x) when upgrading gcc, and you should be fine for [most of](https://bugs.gentoo.org/show_bug.cgi?id=542482) [the cases](https://bugs.gentoo.org/show_bug.cgi?id=566328), but your mileage may vary.

**Comment by bpinto** [comment]
Do you think I should upgrade to gcc 5 as of now?

**Comment by Dr-Terrible** [comment]
I'm using `gcc:5.3.0` as my default compiler for a year now, and I had problems only with an handful of packages so far (and only at the very beginning of the upgrade process because the ebuilds didn't provide patches for gcc5/6 back then). Since then, I have already compiled the entire world at least twice without compilation issues of any sort, or segmentation faults when running apps.

So I'm pretty sure you'll be fine, provided that you follow the aforementioned guide for [upgrading gcc:4 to gcc:5](https://wiki.gentoo.org/wiki/Upgrading_GCC#The_special_case_C.2B.2B11_.28and_C.2B.2B14.29); in particular the part:

```shell
root $ revdep-rebuild --library 'libstdc\+\+.so.6' -- --exclude gcc
```

Just in case, verify that you aren't using one the packages already known to be broken and without a proper fix: https://bugs.gentoo.org/show_bug.cgi?id=536984  (see the section "Depends on:" and move the mouse over the list of *not closed* reports, you should see the package name). Unless you're using some obscure library/app whose last release was made when dinosaurs roamed the earth, then you should be OK :D

So far, only `skype` seems to have a critical issue (due to Qt4 and USE flag `exceptions`, see bug report 546746); all the rest of the open issues are about not common libs/tools.

**Comment by Dr-Terrible** [comment]
> Is it better than having two GCC versions installed?

For now, keep gcc:4 too together with gcc:5; just in case you need it.

At the moment, there is an ongoing discussion among Gentoo's developers about stabilizing gcc:5 in the near future, so we'll get a stable gcc:5.x in the next few months. When that happens, you can safely remove gcc:4 because it will be redundant ;)

**Comment by bpinto** [comment]
Oh that's awesome news!

By the way, this is how I solved it:

```
$ cat /etc/portage/env/gcc-5.4.0 
CC="/usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0/gcc" 
CXX="/usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0/g++"

$ cat /etc/portage/package.env 
x11-misc/polybar gcc-5.4.0
```

**Comment by bpinto** [comment]
Compilation succeeded. If there is something else, I'll open another issue! Thanks for the chat.

**Comment by Dr-Terrible** [comment]
You're welcome :)
